[config]
schemaVersion = "0.0.1"

[package]
namespace = "ykysnk"
name = "No_Enemies"
versionNumber = "0.0.1" # will be replaced
description = "Nothing happened in Hollow Knight: Silksong"
websiteUrl = "https://github.com/T2PeNBiX99wcoxKv3A4g/HKSS.NoEnemies"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack_Silksong = "5.4.2304"
ykysnk-BepinExUtils = "0.7.10"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["hollow-knight-silksong", ]
[publish.categories]
hollow-knight-silksong = ["mods", "misc", ]
